defaults:
  - base_actor
  - _self_

_target_: verl_vla.workers.config.SFTActorConfig

ema:
  enable: false
  decay: 0.995

data_keys:
  action: action
  action_mask: action_is_pad
  target_value: null

mini_batch_size: 256
micro_batch_size: 32
